apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: {{ .Values.image }}
          ports:
            - containerPort: 8080
          command: ["sh", "-c"]
          args:
            - pip install Flask && python main.py
          env:
            - name: FLASK_APP
              value: "main.py"
            - name: FLASK_RUN_PORT
              value: "8080"
          volumeMounts:
            - name: app-code
              mountPath: /app
      volumes:
        - name: app-code
          configMap:
            name: flask-app-code