apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-contact-points
  namespace: monitoring
  labels:
    grafana_alert: "1"
data:
  contact-points.yaml: |
    apiVersion: 1
    contactPoints:
      - orgId: 1
        name: email admin
        receivers:
          - uid: "admin"
            type: email
            settings:
              addresses: example@gmail.com
            disableResolveMessage: false