apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-pv
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.persistence.size }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/jenkins-volume/